timezone: Australia/Melbourne

permalink: /:title

collections:
  posts:
    output: true
    permalink: /articles/:title

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-coffeescript

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]

# SCSS
sass:
  style: compressed

# SEO
title: Labor YIMBY
tagline: Portfolio
description: A non-factional, non-affiliated advocacy group within the Australian Labor Party fighting for housing abundance.
logo: /assets/img/logo.svg
locale: en-AU
